// <auto-generated />
namespace Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Resolve_Merge_conflict_Migraiton : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resolve_Merge_conflict_Migraiton));
        
        string IMigrationMetadata.Id
        {
            get { return "201704192317179_Resolve_Merge_conflict_Migraiton"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
